//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invecam_S_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo_Product
    {
        public int comboID { get; set; }
        public int productID { get; set; }
        public Nullable<int> quantityPCombo { get; set; }
        public string descriptionCP { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual Product Product { get; set; }
    }
}
