//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invecam_S_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employeesID { get; set; }
        public string employeeName { get; set; }
        public string employeeLastName { get; set; }
        public string e_UserName { get; set; }
        public string e_Password { get; set; }
        public string typeEmployee { get; set; }
    }
}
