//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invecam_S_A
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Almacenes_DB2Entities : DbContext
    {
        public Almacenes_DB2Entities()
            : base("name=Almacenes_DB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Combo_Product> Combo_Product { get; set; }
        public virtual DbSet<Combo> Combos { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<Detail_Order> Detail_Order { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Products> Products1 { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Routes_Delivery> Routes_Delivery { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
