//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invecam_S_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Detail_Order = new HashSet<Detail_Order>();
        }
    
        public int orderID { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public string status1 { get; set; }
        public string status2 { get; set; }
        public string code { get; set; }
        public string deliveryDay { get; set; }
        public string typeOfSale { get; set; }
        public Nullable<int> totalDiscount { get; set; }
        public int routeID { get; set; }
        public int customerID { get; set; }
        public int deliveryID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Delivery Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Order> Detail_Order { get; set; }
        public virtual Route Route { get; set; }
    }
}
